# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

mkdocs:
  configuration: mkdocs.yml
