language: python
cache: pip
before_script:
  - pip install --upgrade tox setuptools virtualenv
  # we use tclsh in tests
  - sudo apt-get -y install tcl

script: tox

matrix:
  include:
    - name: "Python 3.5 Tests"
      python: "3.5"
      env: TOXENV=py35
    - name: "Python 3.6 Tests"
      python: "3.6"
      env: TOXENV=py36
    - name: "Python 3.7 Tests"
      python: "3.7"
      env: TOXENV=py37
    - name: "Python 3.8 Tests"
      python: "3.8"
      env: TOXENV=py38

    - name: "Lint and Code Style"
      python: "3.7"
      env: TOXENV=lint
    - name: "Documentation"
      python: "3.7"
      env: TOXENV=docs
    - name: "Build"
      python: "3.7"
      env: TOXENV=build
