site_name: quartustcl
theme: readthedocs
nav:
  - index.md
  - example-memory.md
  - reference.md

extra_css:
  - css/custom.css

markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - mkautodoc
