[tox]
minversion = 2.3.1
envlist =
    lint,docs,build,
    py39,py310,py311,py312,py313,py314

[testenv]
commands = python -m tests

[testenv:lint]
basepython = python3
skip_install = true
deps =
    flake8
    flake8-colors
    flake8-import-order
    pep8-naming
commands =
    flake8 quartustcl/ tests/

[testenv:docs]
basepython = python3
deps = .[docs]
commands =
    mkdocs -q build

[testenv:build]
basepython = python3
skip_install = true
deps =
    build
commands =
    python -m build
